### PR TITLE
HWKAPM-496 Add lifecycle support for initialising resolved services

### PR DESCRIPTION
**Pull request by objectiser**

### CODE REVIEW

**Comment by objectiser** [comment]
@lucasponce Hi Lucas, would you mind having a quick look at this PR?

I'm adding support for Kafka as a backbone event processing infrastructure, which resulted in a number of indirect changes - so now I'm splitting those changes out into specific PRs, of which this it the first.

**Comment by lucasponce** [comment]
LGTM
Travis is complaining but I guess it's unrelated to the code.

**Comment by objectiser** [comment]
@lucasponce Thanks Lucas - yes travis periodically has problems building the UI, as NPM fails. I'll rerun just to see if I can get a clean run.

**Comment by objectiser** [comment]
Travis build failed due to unrelated code - the UI (npmjs) had connection fails.

**Pull request merged**
