### PR TITLE
HWKAPM-589 | Instrumentation test framework failing due to "Address already in use"

### PR DESCRIPTION
**Pull request by pavolloffay**
https://issues.jboss.org/browse/HWKAPM-589

* enables instrumentation framework tests

Review notes: 
please run:
* `docker network rm hawkular-apm`
* `mvn clean install` in instrumentation-framework directory
* `docker network ls` -> there should not be `hawkular-apm` network

### CODE REVIEW

**Comment by objectiser** [comment]
@pavolloffay The is no network after running the three steps, however my test still fails:

INFO: Removing network: hawkular-apm
org.hawkular.apm.tests.dockerized.exception.EnvironmentException: [docker-compose, -f, /home/gbrown/repositories/hawkular/hawkular-apm/tests/instrumentation-framework/target/test-classes/testTicketMonsterDockerCompose/docker-compose.yml, exec, ticket-monster, bash, -c, mkdir /opt/hawkular-apm-test-local47e7fa9d-7a21-4c82-bb6f-9170c33e4f95 && cp /opt/hawkular-apm-test/action1.sh /opt/hawkular-apm-test-local47e7fa9d-7a21-4c82-bb6f-9170c33e4f95 && chmod +x /opt/hawkular-apm-test-local47e7fa9d-7a21-4c82-bb6f-9170c33e4f95/action1.sh && /opt/hawkular-apm-test-local47e7fa9d-7a21-4c82-bb6f-9170c33e4f95/action1.sh] did not return 0, actual = 1
	at org.hawkular.apm.tests.dockerized.environment.DockerComposeExecutor.runShellCommand(DockerComposeExecutor.java:122)

**Comment by pavolloffay** [comment]
@objectiser Could you please provide full log file?

**Comment by objectiser** [comment]
@pavolloffay log attached to jira.

**Comment by pavolloffay** [comment]
@jpkrohling could you please run it too?

**Comment by jpkrohling** [comment]
I don't have the `hawkular-apm` network, and tests are fine:

```
Number of successful test cases: 1


Scenarios results:
Successful: 2, Failed: 0


Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 145.758 sec - in org.hawkular.apm.tests.dockerized.InstrumentationTest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by jpkrohling** [comment]
Jenkins also shows no test failures:
https://jenkins.torii.gva.redhat.com/job/hawkular-apm-pr-builder/25/

@objectiser , do you have `docker-compose` in your `PATH`?

**Comment by jpkrohling** [comment]
I just noticed that the instrumentation framework did *not* run on Jenkins: 
https://jenkins.torii.gva.redhat.com/job/hawkular-apm-pr-builder/25/org.hawkular.apm$instrumentation-test-framework/

**Comment by objectiser** [comment]
@jpkrohling yes, in /usr/bin

**Comment by objectiser** [comment]
@pavolloffay Works fine now with docker-compose 1.8.0. Merge when rebased.

**Pull request merged**
