### PR TITLE
HWKAPM-858 : Don't draw line on gaps missing data

### PR DESCRIPTION
**Pull request by ammendonca**
This fills the completion time arrays with timestamps and null value
based on timestamps present in other selected series.

### CODE REVIEW

**Comment by objectiser** [comment]
@ammendonca Seems to be an issue - I start a v2 of account-manager and run for a while, then stop it, and restarted it twice for less than 10 seconds each time (with longer gaps). When the services page updated, the dots showed in the top chart, but there was no data in the bar chart below for the v2 of account manager.

service-zero-issue

**Comment by ammendonca** [comment]
@objectiser do you have the data for this ? The TX/Faults count chart was not touched, not sure if it is related. What happens without this PR ?

**Comment by objectiser** [comment]
[traces150217.json.zip](https://github.com/hawkular/hawkular-apm/files/777927/traces150217.json.zip)

The trace data - hopefully you will be able to try it - I'll also try it out tomorrow morning.

**Comment by ammendonca** [comment]
Thanks. I was able to replicate and confirm that without modifications the data on below chart shows (with the changes, it seems to show the data, but on the wrong timespan). Will investigate tomorrow.

**Comment by ammendonca** [comment]
Updated. Should be fixed now:

image

**Comment by objectiser** [comment]
@ammendonca Looking at this image, wondering if it is possible to align the charts so there X axis starts at the same point? The bottom chart is slightly to the left.

**Comment by ammendonca** [comment]
@objectiser indeed... but I guess that comes from the y axis labels being larger on the top chart. I'll see what can be done :)

**Comment by ammendonca** [comment]
image

**Comment by objectiser** [comment]
@ammendonca LGTM.

@jpkrohling Ok with you?

**Comment by jpkrohling** [comment]
LGTM

**Comment by objectiser** [comment]
@ammendonca Thanks!

**Pull request merged**
