### PR TITLE
HWKAPM-834 Add REST endpoint for retrieving service endpoint response…

### PR DESCRIPTION
**Pull request by objectiser**
… timeseries stats

### CODE REVIEW

**Comment by objectiser** [comment]
@jpkrohling I think you are thinking about the fragment completion time - that was removed to simplify the processing. So this functionality now just queries the existing node details for the service endpoints.

**Comment by jpkrohling** [comment]
Right, yes. In that case, LGTM

**Comment by objectiser** [comment]
btw I need to look into the jenkins failures - as it might be the new test is affecting the existing ones somehow.

**Comment by objectiser** [comment]
@jpkrohling Ok thanks - I'll just see if I can get the tests working on jenkins.

**Comment by objectiser** [comment]
retest this please

**Pull request merged**
