### PR TITLE
HWKAPM-799 Return the completion times in descending time order, so m…

### PR DESCRIPTION
**Pull request by objectiser**
…ost recent first

### CODE REVIEW

**Comment by objectiser** [comment]
@pavolloffay Could you review please?

**Comment by pavolloffay** [comment]
Are results on component tab ordered by descending time? And possibly other tables in APM?

**Comment by objectiser** [comment]
No other table is ordered on timestamp. The component table is showing aggregated results.

**Comment by pavolloffay** [comment]
Thanks, it's fine to go in.

**Comment by objectiser** [comment]
retest this please

**Comment by objectiser** [comment]
@pavolloffay Thanks. Merging as unrelated test failures.

**Pull request merged**
