### PR TITLE
HWKAPM-786 Deployment Profiles

### PR DESCRIPTION
**Pull request by ammendonca**

### CODE REVIEW

**Comment by objectiser** [comment]
@ammendonca Good start - main issue I found was trying to select the service and then version - when the refresh cycle occurred it just cleared the service (and version field disappeared) - many times just as I was about to press the add button :)

Any way to keep the fields stable if the refreshed values haven't changed?

**Comment by ammendonca** [comment]
@objectiser Yeah, I've noticed that as well, will see how to fix.

**Comment by ammendonca** [comment]
Should be fixed.

**Comment by objectiser** [comment]
@ammendonca The retry issue seems to be fixed, although I need to update the REST endpoints before we merge - will hopefully get it sorted today.

**Comment by objectiser** [comment]
@ammendonca After fixing the service deployment info to use service endpoints instead of trace completion info (now available in master), I updated the timeseries endpoint to /hawkular/apm/analytics/endpoint/response/statistics (instead of trace/completion/statistics). I now see issues when selecting from two services with different buildstamp/versions. It seems to go between no data being displayed, to just the first service/version being displayed.

**Comment by objectiser** [comment]
services

**Comment by objectiser** [comment]
@ammendonca LGTM :+1:  Attaching example image. Will wait until @jpkrohling has tried it out before merging.

**Comment by objectiser** [comment]
servicesui

**Comment by ammendonca** [comment]
Fixed an issue with TX/Fault Count bars not stacking properly, here's an updated screenshot

image

**Comment by jpkrohling** [comment]
image

(are you serious that I can just Ctrl+V an image to this comment box???)

It looks good, specially for a first iteration. I deployed our vertx examples, using your commit as the base for the APM image and deployed everything in OpenShift. What you see on the image above is the result after a few minutes of `genorders.sh`. On the first minutes, you can see the build 1, later on replaced by build 2.

**Comment by jpkrohling** [comment]
image

We should probably limit the number of bars , though.

**Comment by objectiser** [comment]
@ammendonca Found one issue - if there is no actual data associated with a service/version (e.g. if no interactions occur after a while, within the defined timespan), then you get:

serviceui2

**Comment by jpkrohling** [comment]
+1 to get this merged and let the minor issues be handled in other JIRAs.

**Comment by objectiser** [comment]
@ammendonca Thanks Alex, great job!

**Comment by objectiser** [comment]
@ammendonca Created https://issues.jboss.org/browse/HWKAPM-842 for the 'no data' issue.

**Comment by ammendonca** [comment]
Thanks, will have a look at the "no data" issue.

**Pull request merged**
