### PR TITLE
Update & Cleanup frontend dependencies definitions

### PR DESCRIPTION
**Pull request by ammendonca**
- Update to patternfly & angular-patternfly 3.17.0;
- Align angular versions to 1.5.0;
- Update angular-bootstrap to 0.14.3;
- Update other dependencies as required by 3rd party deps;
- Remove some unused deps (hawkular-charts, inifinite-scroll, md5, etc.);

### CODE REVIEW

**Comment by objectiser** [comment]
@ammendonca Most things seemed to work fine, but both the Distributed Tracing page, and Instance diagrams, didn't show any of the tooltips.

**Comment by ammendonca** [comment]
Indeed, strange. I assumed tooltips were working generally as they work on the Transactions "Duration". Will check.

**Comment by ammendonca** [comment]
Updated, HTML tooltips have changed in version 0.14.x

**Comment by objectiser** [comment]
@ammendonca Thanks!

**Pull request merged**
