### PR TITLE
Test modules structure refactoring

### PR DESCRIPTION
**Pull request by pavolloffay**
Now all source code is being compiled even without `-Ptests` profile. 

What this PR includes:
* Profile `tests` renamed to `itest` (to keep consistent with other hawkular projects)
* All integration tests renamed to `*ITest.java`
* Profile `itest` is defined in separate poms not in parent.
* Test artifacts can define unit tests and integration tests.
* Introduced tests-parent-pom
* Mock server moved to the tests-common

### CODE REVIEW

**Comment by objectiser** [comment]
@pavolloffay Could you explain the issue you are solving in more detail, as not currently clear.

At present, the integration tests are only compiled when the 'tests' profile is specified.

Why do you want to include unit tests in the separate tests structure? Would it not be better to locate the unit tests with the component they are testing?

**Comment by pavolloffay** [comment]
This PR would allow:
* integration test are compiled with default build (so the whole code base is compiled with default build)
* run only integration tests (`mvn install -Pitest` in `tests` directory)
* it is possible to define unit tests in integration test which are executed with default build (possible use case: unit tests for testing instrumentation test framework)
* cleaner project structure

**Comment by objectiser** [comment]
@pavolloffay LGTM :+1: 

Hopefully the test structure will be further simplified when the instrumentation tests are done through example applications - although we will need to see, and it may still require specific tests.

**Comment by pavolloffay** [comment]
@objectiser Thanks!

**Pull request merged**
