### PR TITLE
HWKAPM-561 Updated vertx HTTP rules to use uri() method instead of in…

### PR DESCRIPTION
**Pull request by objectiser**
…ternal request field which has changed in the vertx 3.3.x version

### CODE REVIEW

**Comment by objectiser** [comment]
@pavolloffay Another quick one to review please?

**Comment by pavolloffay** [comment]
LGTM :+1:

**Comment by jotak** [comment]
I'll test with my use case (currently building...), I'll let you know

**Comment by jotak** [comment]
Looks good to me. Works with vertx 3.3.2, the initial exception is not thrown anymore. Data is received by the APM server.

**Comment by objectiser** [comment]
Thanks @jotak and @pavolloffay .

**Pull request merged**
