### PR TITLE
HAWKULAR-1138 move to okhttp 3.x

### PR DESCRIPTION
**Pull request by jmazzitelli**

### CODE REVIEW

**Comment by objectiser** [comment]
@jmazzitelli LGTM. Will parent pom be released before this is merged?

**Comment by jmazzitelli** [comment]
Yes, parent-pom will be. See the JIRA and my thread on hawkular-dev for what is going on with all these PRs to move okhttp from 2.x to 3.x.

**Comment by jmazzitelli** [comment]
There is going to be a problem - when moving to commons 0.9.1 this compile error will occur:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project hawkular-apm-server-rest: Compilation failure: Compilation failure:
[ERROR] /home/mazz/source/hawkular-apm/server/rest/src/main/java/org/hawkular/apm/server/rest/filter/CorsFilter.java:[24,38] cannot find symbol
[ERROR] symbol:   class AbstractCorsResponseFilter
[ERROR] location: package org.hawkular.jaxrs.filter.cors
[ERROR] /home/mazz/source/hawkular-apm/server/rest/src/main/java/org/hawkular/apm/server/rest/filter/CorsFilter.java:[25,38] cannot find symbol
[ERROR] symbol:   class AbstractOriginValidation
[ERROR] location: package org.hawkular.jaxrs.filter.cors
[ERROR] /home/mazz/source/hawkular-apm/server/rest/src/main/java/org/hawkular/apm/server/rest/filter/CorsFilter.java:[32,33] cannot find symbol
[ERROR] symbol: class AbstractCorsResponseFilter
[ERROR] /home/mazz/source/hawkular-apm/server/rest/src/main/java/org/hawkular/apm/server/rest/filter/CorsFilter.java:[59,57] cannot find symbol
[ERROR] symbol:   class AbstractOriginValidation
[ERROR] location: class org.hawkular.apm.server.rest.filter.CorsFilter
```

This seems to be an across-the-board issue. inventory is fixing it this way: https://github.com/hawkular/hawkular-inventory/pull/323

**Comment by jotak** [comment]
And here is the PR: https://github.com/hawkular/hawkular-apm/pull/719

**Comment by jmazzitelli** [comment]
Nice! Thanks @jotak !!

**Comment by jmazzitelli** [comment]
Since PR #719 is separate from this okhttp upgrade, we'll leave that PR separate and merge it separate. We'll do it first then I'll rebase my PR on it and merge that. We'll do all of this when the time comes - I still need peer review on the rest of my PRs and be given a thumbs up to upgrade okhttp and release parent-pom first.

**Comment by jmazzitelli** [comment]
This is failing because PR #719 needs to be merged first. When that gets merged, rerun travis for this PR and it should go green.

**Pull request merged**
