### PR TITLE
HWKAPM-688 and HWKAPM-683 - Report http query and db query statement …

### PR DESCRIPTION
**Pull request by objectiser**
…as properties in the agent instrumentation rules

### CODE REVIEW

**Comment by objectiser** [comment]
@pavolloffay Could you review please?

Reviewer notes:
* Adding property from instrumentation rules already supported, but wasn't used
* HWKAPM-688 - added database statement as a property
* HWKAPM-683 - added query string as a property

Questions:
* As a separate jira, do we also want to expand out multiple parameters in the query string as separate properties?
* Should the property name for the database statement be standardised? e.g. database.statement - to go along with database.url?

**Comment by pavolloffay** [comment]
As a separate jira, do we also want to expand out multiple parameters in the query string as separate properties? -> Let's use this for now, and see if somebody would need it. It can produce lot of properties.

Should the property name for the database statement be standardised? e.g. database.statement - to go along with database.url? -> +1

Could you extract `http.query` to constants class?

**Comment by pavolloffay** [comment]
Output of itest profile:

`mvn -fn clean install -Pitest > ~/out 2>&1`
[itest.txt](https://github.com/hawkular/hawkular-apm/files/524297/itest.txt)

**Comment by pavolloffay** [comment]
LGTM :+1:

**Comment by objectiser** [comment]
@pavolloffay Thanks, my testing was fine too.

**Pull request merged**
