### PR TITLE
HWKAPM-627 Some of the REST calls were not updated to use the 'criter…

### PR DESCRIPTION
**Pull request by objectiser**
…ia' parameter.

### CODE REVIEW

**Comment by objectiser** [comment]
@pavolloffay Could you review the java parts of this PR please?

@ammendonca Could you review the js parts of this PR please?

Reviewer notes:
* JS: Main purpose of the PR was to fix some REST calls in the UI that were using the old style parameter passing - now supplied with a criteria object (btm.ts).
* JS: In preparation for filter sidebar being used on the btxn pages aswell, have created a top level criteria object in the btm.ts which currently just has the default start time.
* JS: Business txns list is now based on a combination of server defined configs, and dynamic values obtained from reported data - but when navigating to the btminfo page for a btxn that has no config, it just redirected back to the btm page - so changed ts to allow details for dynamic btxn to be shown.
* Java: TransactionInfo updated to include reporting level and whether based on a static (server defined) configuration - this is to provide info required in UI.
* Java: TransactionInfo objects also returned from btxn's configured in the server - which may not have resulted in btxn instances yet - so need to be in the list to allow them to be selected.

**Comment by ammendonca** [comment]
It looks good, according to your notes. When integrating the sidebar we'll get rid of the _local_ $scope.criteria but for now it's ok.

**Comment by objectiser** [comment]
@ammendonca Thanks!

**Comment by objectiser** [comment]
@pavolloffay Thanks!

**Pull request merged**
