### PR TITLE
HWKAPM-865 Ensure incoming hawkular apm header names are capitalised …

### PR DESCRIPTION
**Pull request by objectiser**
…otherwise they don't get recognised

### CODE REVIEW

**Comment by objectiser** [comment]
@jpkrohling Could you review please?

**Comment by objectiser** [comment]
@jpkrohling Updated based on the referenced PR.

**Comment by jpkrohling** [comment]
LGTM, I know it fixes the Spring Boot problem I had back then. If it also handles the concern you had[1] back then, you can close two JIRAs :)

1 - https://github.com/hawkular/hawkular-apm/pull/727#issuecomment-270121266

**Comment by objectiser** [comment]
@jpkrohling Thanks!

**Pull request merged**
