### PR TITLE
HWKAPM-642 | Concurrent modification exception in zipkin completion time processing driver

### PR DESCRIPTION
**Pull request by pavolloffay**
https://issues.jboss.org/browse/HWKAPM-642

@objectiser could you please review?

### CODE REVIEW

**Comment by pavolloffay** [comment]
I do not see the `ConcurrentModificationException` but I think that methods `getTrace` and `getChildren` should be also synchronized.

**Comment by objectiser** [comment]
Yes, I think it may be best to synchronize in those methods aswell. Then should be fine to merge.

**Comment by pavolloffay** [comment]
Similar problem can occur in `InfinispanCommunicationDetailsCache`

**Comment by pavolloffay** [comment]
@objectiser updated. I have user `copyOnWrite` implementations to deal with concurrency.

**Comment by objectiser** [comment]
@pavolloffay LGTM  :+1:

**Pull request merged**
