### PR TITLE
Change swagger doc generation to use groovy script, and update to par…

### PR DESCRIPTION
**Pull request by objectiser**
…ent 43

### CODE REVIEW

**Comment by objectiser** [comment]
@metlos Hi Lukas, could you review this one as its related to the generation of the REST adocs?

If a new build tools / parent are imminent, then I will hold off merging until available.

**Comment by metlos** [comment]
I hope to sort out the build-tools PR today and release build-tools/parent right after that, so maybe it'd be good idea to hold off this one for a while..

**Comment by objectiser** [comment]
@metlos ok to merge?

**Comment by metlos** [comment]
yep, parent 44 should have you covered.

**Comment by objectiser** [comment]
@metlos Thanks, it works great now

**Pull request merged**
