### PR TITLE
HWKAPM-621 Reorganise the APM event processors into a single maven mo…

### PR DESCRIPTION
**Pull request by objectiser**
…dule, and move (with zipkin processors) under the server folder

### CODE REVIEW

**Comment by objectiser** [comment]
@pavolloffay @jpkrohling Consolidated the APM event processors into a single maven module under the server folder - and moved the processors-zipkin module under the server as well. Just wanted to simplify the module structure as there is no reason for them to be separate.

@pavolloffay if you could review, but just want to make sure @jpkrohling is aware so when merged does not come as a surprise :)

**Comment by jpkrohling** [comment]
Just now, I created a `processors/alerts-publisher`, as I thought it would be the best place for it. If I was right, then we'd have a second `processors` now, as we probably want to keep this separated from everything else, linking it only on the `war` module. So, I would almost immediately defeat the purpose of this PR :)

**Comment by jpkrohling** [comment]
Unless, of course, I follow the example of `server/processors-zipkin` and create a `server/processors-alerts` :)

**Comment by objectiser** [comment]
Yes, if you could create in server/processors-alerts :)

**Comment by pavolloffay** [comment]
LGTM :+1:

**Comment by objectiser** [comment]
@pavolloffay Thanks!

**Pull request merged**
