### PR TITLE
HWKAPM-732 Replace the 'business' transaction concept with just simpl…

### PR DESCRIPTION
**Pull request by objectiser**
…e 'transaction'

### CODE REVIEW

**Comment by objectiser** [comment]
@ammendonca Could you please review?

This PR relates to renaming the concept "business transaction" to simply "transaction" - business txn is more aligned with business transaction management which was the original focus of the proiject, but now the focus is the more broad application performance management, use of the more generic term "transaction" seems more appropriate.

**Comment by ammendonca** [comment]
Tested and everything seems to be working fine. There are a few references to `*BT` (eg: `managedBT`, `ignoredBT`, etc) but that may not be an issue ?

**Comment by objectiser** [comment]
@ammendonca Have updated to also change those, if you don't mind checking again. Thanks.

**Comment by objectiser** [comment]
retest this please

**Comment by ammendonca** [comment]
LGTM. Seem to have found two unrelated issues (changing the hostname has no effect and if fault is selected as a property on the sidebar, selecting different TXn won't change the available values), but these are also present in master. Will report and address these issues separately.

**Comment by objectiser** [comment]
@ammendonca Thanks!

**Pull request merged**
