### PR TITLE
Initial commit for Instance Details Diagram View

### PR DESCRIPTION
**Pull request by ammendonca**
Adds a Details column to the Instance Details Table, which when clicked
shows a diagram depicting the nodes which compose the entry.

### CODE REVIEW

**Comment by ammendonca** [comment]
image

**Comment by objectiser** [comment]
Thanks for all the hard work on this Alexandre! I will test it out when back on Wednesday. 

Have a well deserved vacation.

**Comment by objectiser** [comment]
Thanks @ammendonca it works great. There was only one minor issue which I've described in HWKAPM-560 - if I get a chance I'll see if I can fix.

**Comment by objectiser** [comment]
Only other comment is that when displaying more complex diagrams, the height used for displaying the diagram may be limiting. So might need to think about whether navigating to a separate page, or possibly opening up the cell more, may be options.

**Pull request merged**
