### PR TITLE
Update copyright in headers to 2017

### PR DESCRIPTION
**Pull request by objectiser**

### CODE REVIEW

**Comment by objectiser** [comment]
@jpkrohling or @pavolloffay Could one of you review please? Based on John's suggestion, thought best to just update all headers.

**Comment by jpkrohling** [comment]
Updating only the `pom.xml` should be sufficient to avoid the problem @jmazzitelli mentioned. Of course, this solution not only solves that, but also the annoying need to update the header for all touched files. 

I have nothing against this PR, although I personally prefer the annoyance of updating the years on a per-change basis :)

**Comment by pavolloffay** [comment]
I don't have nothing against it either. If I can ask what is John's suggestion, why it's better to update all headers?

**Comment by objectiser** [comment]
John mentioned an issue with the pom headers when releasing - but thought it best to get them all out of the way in one hit :)

**Comment by objectiser** [comment]
Thanks @jpkrohling @pavolloffay

**Pull request merged**
