### PR TITLE
Adjusting margins, width and height of details modal.

### PR DESCRIPTION
**Pull request by cardosogabriel**

### CODE REVIEW

**Comment by objectiser** [comment]
@ammendonca Would you be able to review please?

**Comment by ammendonca** [comment]
LGTM, but .modal-xl is already defined at https://github.com/hawkular/hawkular-apm/blob/c81bcad3dc31af7148a2a3557f3b6ea1e9d3c50a/ui/src/main/scripts/plugins/btm/less/btm.less#L50-L52. It's likely a good idea to keep it in a single place.

`hawkular.less` was intended to be a copy of the same file at main Hawkular UI to keep integration _smooth_. The main file for APM custom styles used to be `btm.less` so it's likely a good idea to make these modifications there ?

**Comment by cardosogabriel** [comment]
@ammendonca , definitely, I'll move the apm styles to the proper file. Thanks!

**Comment by cardosogabriel** [comment]
@ammendonca , removed the APM specific styles that I had written in hawkular.less to btm.less and filter-sidebar.less. Please check.

**Comment by ammendonca** [comment]
LGTM.

**Comment by objectiser** [comment]
@cardosogabriel @ammendonca  Thanks!

**Comment by cardosogabriel** [comment]
Thank you all!

**Pull request merged**
