### PR TITLE
HWKAPM-526 | Span Cache and Infinispan Impl

### PR DESCRIPTION
**Pull request by pavolloffay**
https://issues.jboss.org/browse/HWKAPM-526

### CODE REVIEW

**Comment by pavolloffay** [comment]
@jpkrohling Could you please review?

**Comment by jpkrohling** [comment]
Looks good to me!

**Comment by pavolloffay** [comment]
@jpkrohling Thanks :+1:

**Comment by objectiser** [comment]
Hi Pavol

One change required. Thought I had mentioned it on an email or one of the issues but possibly not.

Span ids are unique except for client and server span pairs which share same id.  If you check the NodeDetailsDeriver in processors/zipkin you will see I modify the client span I'd with a suffix.

This approach needs to be abstracted out into a span utility class to generate the unique id for use in storing spans in the cache and span service. Also some utility function to build a client span I'd for a supplied id to enable the client span to be retrieved. 

This can be applied in separate pr as will be required before implementing processors that use the cache and service.

**Comment by objectiser** [comment]
It's a jira HWKAPM-543.

**Comment by pavolloffay** [comment]
Hello Gary, 

thanks for a review and pointing to this issue. I will rework it on Monday.

Pavol

**Pull request merged**
