### PR TITLE
HWKAPM-462 - Added dev profile, removed default users from main build.

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by jpkrohling** [comment]
On this change, the normal build (`mvn clean install`) will *not* have a default user anymore. A `jdoe`/`password` can be automatically added to the dist if the `dev` profile is used: `mvn clean install -Pdev`.

**Comment by objectiser** [comment]
May need to consider impact on running the integration tests. The dev profile will need to be specified when running integration tests (not sure if there is a way to tie these profiles together?), as it uses the default user.

Also previously I have released with the tests profile specified, so that the release plugin bumps the versions of the test modules. However won't be able to do that now as it wouldn't have the default user defined in the build. Any thoughts on how to deal with this situation?

**Comment by jpkrohling** [comment]
In other Hawkular modules, the test suite module adds a special test user before it starts. Let me see if I can do the same here.

**Comment by jpkrohling** [comment]
By the way: how come the tests passed? O_o

**Comment by jpkrohling** [comment]
Answering to myself: they didn't. This is how Travis runs:

```
script:
- mvn -s .travis.maven.settings.xml verify | grep -vF "[INFO] Downloading:" | grep -vF "[INFO] Downloaded:"; test ${PIPESTATUS[0]} -eq 0
```

**Comment by objectiser** [comment]
Yes, had to stop running integration tests in travis as they hardly ever worked

**Comment by jpkrohling** [comment]
The tests are working, but it would be worth also running it locally before merging.

**Comment by objectiser** [comment]
@jpkrohling Yes builds fine locally. Is the PR complete? So just now requires changes to the docker image? If so, you can merge - or let me know and I will merge.

**Comment by jpkrohling** [comment]
This PR is complete. The Dockerfile change will follow in a separate PR.

**Pull request merged**
