### PR TITLE
Add a 'noui' property to exclude UI from the build

### PR DESCRIPTION
**Pull request by objectiser**

### CODE REVIEW

**Comment by objectiser** [comment]
@jpkrohling @pavolloffay If you add '-Dnoui' to the maven build, then it doesn't build the UI module or include the UI war in the distribution used by the integration tests. Seems to work - let me know your thoughts?

**Comment by jpkrohling** [comment]
So, the travis build will still build the UI? I have two problems with the UI at the moment: the speed of the main build (for local builds) and the reliability of the build on CI environments. Skipping the UI would help only on the first case.

I mean, I'm OK with this PR, as it will certainly help with the local development, but I don't have much hopes that we'll get better CI builds :)

**Comment by objectiser** [comment]
Sorry wasn't clear - the idea would be to prevent CI builds having to build the UI - was just using this to illustrate the approach I had in mind. So if ok, I'll update the travis config.

**Comment by pavolloffay** [comment]
@objectiser if you look at PR https://github.com/hawkular/hawkular-apm/pull/494. The build have never failed for this configuration.

**Comment by objectiser** [comment]
@pavolloffay I think the two issues are separate - the UI isn't used as part of integration testing so adds little value being part of the CI builds. If you think the ubuntu trusty approach is also worth trying, then we could enable that aswell. Are there any potential downsides with it?

Do you have any objections to this PR?

**Comment by pavolloffay** [comment]
If we skip CI for UI on travis it can happen that there could get some code which does not compile (ts rules). UI build on Jenkins is unstable so it would be good to have it here.

Let's give a try #494 and see if it is stable. At the moment it is even faster that this without UI build. 
What do you think @objectiser @jpkrohling ?

**Comment by objectiser** [comment]
@pavolloffay Happy to give it a go - in the meantime I'll revert the travis changes so we could then use this noui flag in jenkins.

**Comment by jpkrohling** [comment]
I'm also OK with @pavolloffay's proposal.

**Comment by jpkrohling** [comment]
For the Jenkins build, I'll try to keep a npm/node distribution cached locally. That will reduce the chances of a the build being affected by network issues.

**Comment by pavolloffay** [comment]
+1 for having it in jenkins.

Is the script `.travis.swagger.sh` still being used? I think documentation does not go to github pages anymore.

**Comment by objectiser** [comment]
@pavolloffay Not sure - we can check and remove separately if necessary.

@jpkrohling That would be good, as it would give the option to build UI on jenkins aswell - but I'll merge this change so that we can also avoid UI build locally to help build time.

**Pull request merged**
