### PR TITLE
HWKAPM-675 Removed fault field from node and derived events, in favou…

### PR DESCRIPTION
**Pull request by objectiser**
…r of reporting faults as a property. This enables multiple faults, reported at different stages of the trace instance, to be collectively associated with the trace instance. This has resulted in fault filtering being removed from the criteria, so a property filter is used instead.

### CODE REVIEW

**Comment by objectiser** [comment]
@pavolloffay Could you review the java code please?
@ammendonca Could you review the changes to the UI please?

Reviewer notes:
* Previously the 'fault' was a field on the Node and other derived events - so only allowed one type of fault to be associated with (for example) the trace completion time.
* This change records faults as a property, so now possible for different faults that occur at various points in a trace instance, to all be associated with the overall trace instance.

Please can you both try building and testing the changes - to make sure the UI still works properly with this underlying change. One approach to test could be to use the examples/vertxopentracing example - the readme includes information on being able to create various faults.

**Comment by objectiser** [comment]
@ammendonca One question - currently the business transaction info page has a pie chart for faults and properties. The faults are represented as before, except under the covers they are represented as properties - which means they also currently show up in the properties dropdown. So was thinking, it doesn't make sense to have faults shown in the properties pie chart (as duplication), so should we just remove 'faut' from the property dropdown (if it is present)?

**Comment by pavolloffay** [comment]
Java side LGTM :+1:

**Comment by ammendonca** [comment]
UI looks good as well

**Comment by objectiser** [comment]
@pavolloffay @ammendonca Thanks!

**Pull request merged**
