### PR TITLE
HWKAPM-768 Fix incomplete retrieval of all relevant fragments related…

### PR DESCRIPTION
**Pull request by objectiser**
… to a trace instance due to a default size of 10 when making the Elasticsearch request

### CODE REVIEW

**Comment by objectiser** [comment]
@jpkrohling Could you review please?

**Comment by jpkrohling** [comment]
Is it possible to add a test for this?

**Comment by objectiser** [comment]
@jpkrohling added test.

**Comment by jpkrohling** [comment]
LGTM!

**Comment by objectiser** [comment]
@jpkrohling Thanks!

**Pull request merged**
