### PR TITLE
Replace srcdeps-maven-plugin with srcdeps core extension

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@objectiser could you please review?

**Comment by objectiser** [comment]
@ppalaga LGTM, but @jpkrohling  could you also take a look?

**Comment by jpkrohling** [comment]
`s/is anough/is enough/` on one of the commit messages

Besides that, I'm not sure we *need* this change, do we? As far as I can see, APM hasn't used src-deps yet and this PR is introducing it. 

All in all, I'm OK with this change, specially because it benefits src-deps itself :)

**Comment by objectiser** [comment]
@jpkrohling Ok thanks - I'm just doing a full build as jenkins wasn't triggered. If ok, I'll merge.

@ppalaga Thanks Peter.

**Pull request merged**
