### PR TITLE
HWKAPM-860 : Services UI support for "Any" buildstamp

### PR DESCRIPTION
**Pull request by ammendonca**
When selecting the "Any" version, all the  named versions are shown, and
new ones will automatically show as well.

### CODE REVIEW

**Comment by ammendonca** [comment]
Example of any being used:
image

I have a question, should "Any" also include unnamed/default version ? My concern is that the usability of this feature will decrease as it makes the chart harder to read, as "All" is the sum of all buildstamps, so will always overlap existing lines, eg:
image

@objectiser, @jpkrohling, @pavolloffay, @theute WDYT ?

**Comment by theute** [comment]
IIUC, I think what you show is what I'd like...
We can select Any + all separately, Any shouldn't include All.

Now, are there better names than any/all ?
If we keep the names, I would personally switch...
"Any" == any version, I'm not interested in details --> "single line/color". 
"All" == show me all versions --> "multiple lines/colors".

But I'm sure it's a matter of taste...

Should it be "combined" and "all" maybe ?

**Comment by pavolloffay** [comment]
What does make sens for me: 

`All`: 
show all versions of given service as separate lines. (and if there is a new version available it should be probably added to the chart)

 `Any`
When I saw it my impression is: would it select randomly some version? Or is it the case when there is no version number available (then I would vote for `undefined`)? 


Would be users interested to see an average of all versions? (shouldn't be this screen used to compare versions? If you insist on it what about
* `All individual` - # if lines = # of versions
* `All average` - one line for all versions

**Comment by objectiser** [comment]
Agree we need clearer terms - individual and consolidated?

**Comment by jpkrohling** [comment]
Other than the naming issue, I think it's a great addition.

**Comment by theute** [comment]
Maybe

1. All separated
2. All combined
3. v1
4. v2
5. v3

**Comment by pavolloffay** [comment]
@jpkrohling agree at least with ES it is possible to do it then why not :+1:

**Comment by ammendonca** [comment]
Updated naming to:

- "All" -> "All (Aggregated)"
- "Any" -> "All (Individually)"

Used this rather combined/separated as the labels won't show the whole thing and the abbreviations are more clear, so it will show "All (Agg)" and "All (Ind)" respectively.

image

**Comment by objectiser** [comment]
@ammendonca Looks good to me - but I'll wait for others to comment.

**Comment by theute** [comment]
In which case would "All (Ind)" appear ? I would assume it would have multiple labels with /v2 /v3...

Other than that, sounds good to me

**Comment by pavolloffay** [comment]
I'm very far from typography expert but maybe lower case would be better?

**Comment by ammendonca** [comment]
@theute, It shows in the grey label (where you can remove the selection), as seen in the last screenshot. In the chart, they do show independently as versions.

**Comment by theute** [comment]
@ammendonca indeed, I missed that and that makes sense. I was looking below the chart.

:+1:

**Comment by objectiser** [comment]
@ammendonca Thanks!

**Pull request merged**
