### PR TITLE
HWKAPM-767 | update version of all zipkin instrumentation libraries

### PR DESCRIPTION
**Pull request by pavolloffay**
* zipkin isntrumentations update
* framework dependencies update
* Resteasy automatically decodes gzip encoded data therefore it is not
        necessary to decode it manually. (Before it produced exception)

Should be reviewed and merged after this: https://github.com/smoketurner/dropwizard-zipkin/pull/18 is merged otherwise it would not be possible to start the server after the environment.

Review notes: 
Build locally all touched images and run polyglot example.

### CODE REVIEW

**Comment by pavolloffay** [comment]
@objectiser could you please review?

**Comment by objectiser** [comment]
retest this please

**Comment by pavolloffay** [comment]
retest this please

**Comment by pavolloffay** [comment]
rebased. `itest`  should pass. I have added new test for gzipped spans.

**Comment by objectiser** [comment]
@pavolloffay LGTM :+1:

**Pull request merged**
