### PR TITLE
HWKAPM-727 Rename 'businessTransaction' field on Trace and derived ev…

### PR DESCRIPTION
**Pull request by objectiser**
…ents to 'transaction'

### CODE REVIEW

**Comment by objectiser** [comment]
@pavolloffay Please can you do a quick review? As discussed on IRC, renaming from 'business transaction' tp just 'transaction'. Business txn term was used initially as the project was focused on business txn management, but when scope widened to application performance management, this area also encompasses business txn monitoring, but the term 'user defined' txns is also used - so decided to just use the term 'transaction' in the model - but also for the transaction config model and UI.

Unfortunately a lot of files have been touched, but it is basically just a rename, so don't spend too much time on the review.

@ammendonca When testing out this change, I found that the candidates page (existing business txn) dropdown was not populated, but was fixed by removing the pf-select. Not sure what the issue was but hopefully the change is ok?

**Comment by pavolloffay** [comment]
There are couple of places where business is mentioned: 
```
hawkular-apm git:(PR670) g grep business 
api/src/main/java/org/hawkular/apm/api/internal/actions/EvaluateURIActionHandler.java:148:                    // If properties extracted, then add to business txn properties, and set the node's
api/src/main/java/org/hawkular/apm/api/model/analytics/TransactionInfo.java:24: * This class represents information related to a business transaction associated with
api/src/main/java/org/hawkular/apm/api/model/config/ReportingLevel.java:27:    /* The activity associated with this business txn is not of interest
api/src/main/java/org/hawkular/apm/api/model/config/ReportingLevel.java:31:    /* Don't report any instances of this business txn, but unlike the
api/src/main/java/org/hawkular/apm/api/model/config/ReportingLevel.java:36:    /* Report all information related to instances of this business txn */
api/src/main/java/org/hawkular/apm/api/model/config/instrumentation/jvm/IgnoreNode.java:22: * with a business fragment that is being captured, then the fragment will be considered
api/src/main/java/org/hawkular/apm/api/model/config/instrumentation/jvm/SetTransaction.java:22: * This type represents the action for setting the business transaction name.
api/src/main/java/org/hawkular/apm/api/model/config/txn/ConfigMessage.java:25: * This class represents a message returned following validation of a business
api/src/main/java/org/hawkular/apm/api/model/config/txn/TransactionConfig.java:28: * This class represents a business transaction configuration.
api/src/main/java/org/hawkular/apm/api/model/config/txn/TransactionSummary.java:25: * This class represents a business transaction summary.
api/src/main/java/org/hawkular/apm/api/model/trace/CorrelationIdentifier.java:144:         * business context (e.g. unique value based on order id). This value
api/src/main/java/org/hawkular/apm/api/model/trace/Message.java:26: * This class represents information exchanged between two participants in the business
api/src/main/java/org/hawkular/apm/api/services/AbstractAnalyticsService.java:361:     * This method obtains the unbound endpoints from a list of business
api/src/main/java/org/hawkular/apm/api/services/AbstractAnalyticsService.java:365:     * @param fragments The list of business txn fragments
api/src/main/java/org/hawkular/apm/api/services/AbstractAnalyticsService.java:403:        // a business txn config
api/src/main/java/org/hawkular/apm/api/services/AnalyticsService.java:45:     * associated with a business transaction).
api/src/main/java/org/hawkular/apm/api/services/AnalyticsService.java:56:     * This method returns the bound endpoints associated with a business
api/src/main/java/org/hawkular/apm/api/services/AnalyticsService.java:68:     * This method returns the business transactions associated with the specified
api/src/main/java/org/hawkular/apm/api/services/AnalyticsService.java:69:     * criteria. Note: the 'business transaction' property in the criteria will be
api/src/main/java/org/hawkular/apm/api/services/AnalyticsService.java:90:     * trace, that were executed during the time range. The business
api/src/main/java/org/hawkular/apm/api/services/AnalyticsService.java:102:     * a fault. The business transaction name must be specified as part of the criteria.
api/src/main/java/org/hawkular/apm/api/services/AnalyticsService.java:122:     * executed during the time range. The business transaction name must be specified
api/src/main/java/org/hawkular/apm/api/services/AnalyticsService.java:133:     * executed during the time range. The business transaction name must be specified
api/src/main/java/org/hawkular/apm/api/services/AnalyticsService.java:146:     * executed during the time range. The business transaction name must be specified
api/src/main/java/org/hawkular/apm/api/services/AnalyticsService.java:157:     * executed during the time range. The business transaction name must be specified
api/src/main/java/org/hawkular/apm/api/services/ConfigurationService.java:38:     * host and server names. Only valid business configurations will be
api/src/main/java/org/hawkular/apm/api/utils/PropertyUtil.java:84:     * The refresh interval to check for updates to the business transaction configuration.
api/src/test/java/org/hawkular/apm/api/model/trace/TraceTest.java:75:        // business transaction, comprised of the start time + duration
client/api/src/main/java/org/hawkular/apm/client/api/reporter/BatchTraceReporter.java:131:                // Initial check, to avoid doing too much work if no business
client/instrumentation-jvm/src/main/resources/apmconfig/jvm/javax/apm-javax-servlet.json:129:          "that this thread is unlinked from the business txn fragment, so that subsequent ",
client/instrumentation-jvm/src/main/resources/apmconfig/jvm/javax/apm-javax-servlet.json:131:          "business txn"
client/instrumentation-jvm/src/main/resources/apmconfig/jvm/rx/apm-rxjava.json:49:          "business transaction starts."
client/instrumentation-jvm/src/main/resources/apmconfig/jvm/rx/apm-rxjava.json:70:          "business transaction starts."
client/instrumenter/src/main/java/org/hawkular/apm/instrumenter/RuleHelper.java:600:     * id (and disassociate the business txn from the current thread).
client/instrumenter/src/main/java/org/hawkular/apm/instrumenter/RuleHelper.java:625:     * id (and disassociate the business txn from the current thread).
client/opentracing/src/main/java/io/opentracing/APMSpan.java:204:            // Propagate trace id, business transaction name and reporting level as creating a
client/opentracing/src/main/java/org/hawkular/apm/client/opentracing/DefaultNodeProcessor.java:47:                    // Check if business transaction name already defined - if not then set on the trace context
client/opentracing/src/main/java/org/hawkular/apm/client/opentracing/NodeProcessor.java:24: * to perform business transaction specific actions. It is also possible that applications
performance/server/src/main/java/org/hawkular/apm/performance/server/Service.java:141:     * @param btxnName The optional business txn name
performance/server/src/main/java/org/hawkular/apm/performance/server/Service.java:154:            // Introduce a delay related to the business logic
server/elasticsearch/src/main/java/org/hawkular/apm/server/elasticsearch/AnalyticsServiceElasticsearch.java:128:            // Copy criteria and clear the business transaction field to ensure all
server/elasticsearch/src/main/java/org/hawkular/apm/server/elasticsearch/AnalyticsServiceElasticsearch.java:129:            // business transactions are returned related to the other filter criteria
server/elasticsearch/src/main/java/org/hawkular/apm/server/elasticsearch/AnalyticsServiceElasticsearch.java:151:        // If config service available, check if there is a business txn config for the list of
server/elasticsearch/src/main/java/org/hawkular/apm/server/elasticsearch/AnalyticsServiceElasticsearch.java:165:            // Add entry for remaining business txn configs
server/elasticsearch/src/test/java/org/hawkular/apm/server/elasticsearch/ConfigurationServiceElasticsearchTest.java:183:        // Get valid business txns
server/processors/src/main/java/org/hawkular/apm/server/processor/tracecompletiontime/TraceCompletionTimeDeriver.java:27: * This class represents the end to end business transaction completion time deriver.
tests/agent-opentracing/src/test/java/org/hawkular/apm/tests/agent/opentracing/server/http/JavaxServletSyncServerITest.java:225:        // Check stored business transactions (including 1 for the test client)
tests/container/jetty/src/test/java/org/hawkular/apm/tests/client/jetty/ClientJettyReaderWriterAsyncITest.java:207:        // Check stored business transactions (including 1 for the test client)
tests/container/jetty/src/test/java/org/hawkular/apm/tests/client/jetty/ClientJettyReaderWriterITest.java:205:        // Check stored business transactions (including 1 for the test client)
tests/container/jetty/src/test/java/org/hawkular/apm/tests/client/jetty/ClientJettyStreamAsyncITest.java:210:        // Check stored business transactions (including 1 for the test client)
tests/container/jetty/src/test/java/org/hawkular/apm/tests/client/jetty/ClientJettyStreamITest.java:195:        // Check stored business transactions (including 1 for the test client)
tests/container/jetty/src/test/java/org/hawkular/apm/tests/client/jetty/ClientJettyStreamITest.java:280:        // Check stored business transactions (including 1 for the test client)
tests/container/standalone/src/test/java/org/hawkular/apm/tests/client/jav/ClientJavaMainITest.java:100:        // Retrieve stored business transaction
tests/dist/src/test/java/org/hawkular/apm/tests/dist/ConfigurationServiceITest.java:196:        // these waits are part of the business logic and shouldn't be changed
```

**Comment by objectiser** [comment]
@pavolloffay Updated to change majority of the comments - have left a couple that are still appropriate usage. Will sort out the remainder of the UI rename in a separate PR.

**Comment by ammendonca** [comment]
@objectiser, pf-select has issues with certain types of data, for now it's ok to remove, I'll investigate what is the issue.

**Comment by pavolloffay** [comment]
@objectiser thanks, it looks much better now: 
```
 hawkular-apm git:(PR670) g grep business | grep java                                                           
api/src/main/java/org/hawkular/apm/api/model/trace/CorrelationIdentifier.java:144:         * business context (e.g. unique value based on order id). This value
client/instrumentation-jvm/src/main/resources/apmconfig/jvm/javax/apm-javax-servlet.json:129:          "that this thread is unlinked from the business txn fragment, so that subsequent ",
client/instrumentation-jvm/src/main/resources/apmconfig/jvm/javax/apm-javax-servlet.json:131:          "business txn"
client/instrumentation-jvm/src/main/resources/apmconfig/jvm/rx/apm-rxjava.json:49:          "business transaction starts."
client/instrumentation-jvm/src/main/resources/apmconfig/jvm/rx/apm-rxjava.json:70:          "business transaction starts."
performance/server/src/main/java/org/hawkular/apm/performance/server/Service.java:141:     * @param btxnName The optional business txn name
performance/server/src/main/java/org/hawkular/apm/performance/server/Service.java:154:            // Introduce a delay related to the business logic
tests/dist/src/test/java/org/hawkular/apm/tests/dist/ConfigurationServiceITest.java:196:        // these waits are part of the business logic and shouldn't be changed
```

I think it can go :+1: , Nice work lot of changes :+1:

**Comment by objectiser** [comment]
@pavolloffay Thanks!

**Pull request merged**
