### PR TITLE
exit APM mock server only if was running

### PR DESCRIPTION
**Pull request by pavolloffay**
@objectiser could you please review?

### CODE REVIEW

**Comment by objectiser** [comment]
@pavolloffay Just curious, under what circumstances was the server not set up?

**Comment by pavolloffay** [comment]
It is causing NPE in instrumentation framework

**Comment by objectiser** [comment]
Ok fine to merge then. Travis is still messing up :(

**Comment by pavolloffay** [comment]
@objectiser thanks!

**Pull request merged**
