### PR TITLE
HWKAPM-803 - Normalize header and constant before the string comparison.

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by objectiser** [comment]
@jpkrohling This change is only normalising the header when checking if the header is trace state. But when (for example) the trace id is extracted in TraceContext and APMSpan, it is still using the constant. So if they did not match, it wouldn't find the value?

**Comment by jpkrohling** [comment]
Indeed, I didn't pay enough attention to the other places consuming this map. On my local environment, I worked this around by converting the keys to upcase before populating to the map that is visible to the APM related code. I'll mark this as "do not merge" for now, as it needs more investigation on where related changes are required.

**Comment by objectiser** [comment]
Which framework(s) is making this change from uppercase to something else?

**Comment by jpkrohling** [comment]
I see those as lowercase on the `ola` service, which is using Spring Boot. If those are converted or if Spring Boot received those as lower case already, it's still not clear to me :)

**Comment by objectiser** [comment]
Closing as fixed by https://github.com/hawkular/hawkular-apm/pull/778

**Pull request closed without merging**
