### PR TITLE
HWKAPM-603 Change from POST to GET and encode the criteria as a query…

### PR DESCRIPTION
**Pull request by objectiser**
… parameter

### CODE REVIEW

**Comment by objectiser** [comment]
@ammendonca Hi Alex, could you take a quick look at this PR - its to change calls to analytics service from POST to GET encoding the criteria as a query parameter. Tested against the booker example and seemed to work fine.

**Comment by objectiser** [comment]
@ammendonca Tried out this code but it didn't seem to like it. Is it ok to merge as is for now, and look to improve the code later?

**Comment by ammendonca** [comment]
Sure, I was afraid that'd be the case, as angular does some behind the scenes work on encoding the params.

**Comment by objectiser** [comment]
@ammendonca Thanks!

**Pull request merged**
