### PR TITLE
Minor fix related to microseconds change - timestamp in instance tabl…

### PR DESCRIPTION
**Pull request by objectiser**
…e needs to be converted back to milliseconds to display correctly

### CODE REVIEW

**Comment by objectiser** [comment]
@ammendonca Could you review please? Unfortunately I missed this timestamp on the instance table when doing the previous change.

**Comment by pavolloffay** [comment]
retest this please

**Comment by ammendonca** [comment]
LGTM

**Comment by objectiser** [comment]
@ammendonca Thanks!

**Pull request merged**
