### PR TITLE
HWKAPM-744 Change the 'TraceCompletionTime' to just 'TraceCompletion'…

### PR DESCRIPTION
**Pull request by objectiser**
… to reflect the fact that it is really an event indicating the trace has completed. The time aspect (i.e. the duration) is just one of the pieces of information conveyed by this event.

### CODE REVIEW

**Comment by objectiser** [comment]
@jpkrohling Could you review please? Based on our discussion earlier this week, have changed the term 'TraceCompletionTime' to 'TraceCompletion' throughout.

Couple of points:
* Currently haven't changed the REST endpoint `analytics/completion/times` which returns the list of filtered documents, as there are other variations, e.g. `completion/faults`, `completion/statistics`, `completion/percentiles`, etc. Could change it to `analytics/completion/events`?
* I've created a jira to discuss what to do with the similar FragmentCompletionTime (https://issues.jboss.org/browse/HWKAPM-745) options being to rename or potentially remove the concept all together.

**Comment by pavolloffay** [comment]
Isn't more appropriate name for this `TraceDuration` ?

**Comment by objectiser** [comment]
@pavolloffay It represents more of an event related to the completion of a trace, rather than any particular field within the event. TraceDuration would be focusing again on the time aspect rather than the event itself.

**Comment by objectiser** [comment]
@jpkrohling Ok thanks - I'll delay merging until possibly tomorrow to see if there is a better term.

**Comment by pavolloffay** [comment]
@objectiser IIRC the most important data it is carrying is trace duration. If is we plan to add some other fields then more generic name would be appropriate. If we change the trace completion time processing to send this event periodically on new incoming span data then the name `TraceCompletion` can be misleading.

**Comment by objectiser** [comment]
@pavolloffay Good point - forgot about the fact that we may publish intermediate results - but still may be more appropriate to have a better name.

**Comment by objectiser** [comment]
@jpkrohling After further thought, I still think the name is appropriate, as primarily it is the name being used on event distribution via JMS and to the alerts engine - in both cases we want any 'subscribers' to the event to be as specific as possible (to minimise unnecessary event processing) rather than listing for a more generic TraceEvent that could potential represent different states.

@pavolloffay I need to discuss this situation with the Alerts team to understand the impact of receiving multiple events - but each event still represents a trace completion and there is no guarantee that there will be multiple events, we may still just send one event per trace instance. Each subsequent (if required) will only represent an update on the previous event state - but they are still representing the same thing, the trace completion data.

**Comment by jpkrohling** [comment]
> I still think the name is appropriate

In that case, I'm fine with the change.

**Comment by objectiser** [comment]
retest this please

**Comment by pavolloffay** [comment]
@objectiser I think it wouldn't be a problem to send multiple events for one trace and re-evaluate conditions in Alerts (from what I know when I integrated dataminig with alerts). Actually it would trigger the alert when for the first time conditions are met, following trace durations would be always > than previous and alerts has capabilities to do not trigger next alerts if it already triggered.

**Comment by pavolloffay** [comment]
I would vote for `TraceEvent` rather than `TraceCompletion`.

**Comment by objectiser** [comment]
@pavolloffay Yes looks like it can be supported based on Lucas's response on the alerts jira - plus we have a demo organised for tomorrow to go through this scenario.

I'll merge this PR now.

**Comment by objectiser** [comment]
@pavolloffay Just seen your additional comment - the problem is that implies different types of TraceEvent may get reported on that same JMS destination or Alert type - and as explained in response to Juca, it would be better to have focused channels for the different 'trace event types' (if there are ever any others) so that subscribers to those channels (e.g. alert triggers) only process the specific events they are interested in.

**Comment by pavolloffay** [comment]
Therefore I would name this `TraceDuration` as it will probably be used to evaluate overall duration of the trace. Do you see that this event would contain another "derived" information?

**Comment by objectiser** [comment]
@jpkrohling How do you feel about `TraceDuration`?

**Comment by jpkrohling** [comment]
Based on your previous explanation (https://github.com/hawkular/hawkular-apm/pull/685#issuecomment-260975262) , I prefer the `Completion` than `Duration`.

**Comment by objectiser** [comment]
@pavolloffay @jpkrohling thanks for the review/discussion.

**Pull request merged**
