### PR TITLE
HWKAPM-844 Fix http url connection rules when just accessing getRespo…

### PR DESCRIPTION
**Pull request by objectiser**
…nseCode()

### CODE REVIEW

**Comment by objectiser** [comment]
@jpkrohling Could you review please?

**Comment by jpkrohling** [comment]
The code looks sane, but I'm not sure I understand the problem it's fixing.

**Comment by objectiser** [comment]
@jpkrohling If 'getResponseCode' is used after getting the URL connection, it will result in the http request being sent - but the previous rules were not detecting that situation - only when a top level connect, getInputStrream or getOutputStream were used.

**Comment by jpkrohling** [comment]
Right, makes sense then :)

**Comment by objectiser** [comment]
@jpkrohling Thanks!

**Pull request merged**
