### PR TITLE
HWKAPM-571 | Configuration driven mechanism for mapping Span annotations to APM information

### PR DESCRIPTION
**Pull request by pavolloffay**
https://issues.jboss.org/browse/HWKAPM-571

### CODE REVIEW

**Comment by pavolloffay** [comment]
@objectiser could you quickly look at it if the mapping is ok? Currently it only loads mapping from mapping file these mappings are not used in the code yet.

**Comment by objectiser** [comment]
@pavolloffay Good start - after a quick review the only thing I would change is put the iteration of the binary annotations as an outer loop, then retrieve the mapping for the key, and then perform each step of the mapping (i.e. component/endpoint/properties/details) within that scope - rather than performing the iteration of binary annotations and get mapping for each step.

**Comment by pavolloffay** [comment]
The most efficient way would be: 

`MappingResult getMapping(List<BinaryAnnotation> baList)` where the `MappingResult` contains properties, details... One thing I don't like that this `getMapping` would have to be called in each deriver. Solution to that would be make binary annotations of span immutable and store this result there.

**Comment by objectiser** [comment]
:+1: Lets add the processed data to the Span before it is republished to the derivers  - only issue is that some of the data will be duplicated - but we can review the performance at a later stage.

**Comment by pavolloffay** [comment]
What should happen to BA which are not listed in mapping file. Should be added to properties and node details map?

**Comment by objectiser** [comment]
I think for now the default action, if the BA has been explicitly listed to be ignored, should be to add to details map.

**Comment by pavolloffay** [comment]
@objectiser could you please re-review?

**Comment by objectiser** [comment]
@pavolloffay Thanks!

**Pull request merged**
