### PR TITLE
HWKAPM-811 Store HTTP status code in OpenTracing standard tag 'http.s…

### PR DESCRIPTION
**Pull request by objectiser**
…tatus_code' and don't use 'fault' tag for communication protocol errors, only business protocol level faults

### CODE REVIEW

**Comment by objectiser** [comment]
@pavolloffay I haven't updated the zipkin constant for http.status_code - should this change be included in this PR or separate?

**Comment by pavolloffay** [comment]
LGTM :+1: 

In separate PR is even better :+1: 

CI is again having bad days :disappointed: 

`Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project hawkular-apm-ui: Failed to run task: 'npm install' failed. (error code 1) -> [Help 1]`

**Comment by objectiser** [comment]
retest this please

**Comment by objectiser** [comment]
@pavolloffay Thanks!

I've created HWKAPM-818 for the zipkin constants.

**Comment by objectiser** [comment]
Test failures are unrelated, so will merge.

**Pull request merged**
