### PR TITLE
Caching node to the user's home

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by jpkrohling** [comment]
Second build, with `-Pcache`:
```
[INFO] Total time: 03:43 min
```

Third build, with `-Pcache,tests`:
```
[INFO] Total time: 06:09 min
```

I believe the `-Pcache` won't have any effects on CI, as CI's should start from scratch, so, it would always rebuild the UI. But for local development, this should also help.

**Comment by jpkrohling** [comment]
retest this please

**Comment by pavolloffay** [comment]
@jpkrohling is there way to tell Jenkins not to clean UI artifact? If it does not clean then maven-frontend-plugin does not download and install npm, bower..

**Comment by jpkrohling** [comment]
The `-Pcache` should do exactly that, but for a CI environment, starting with a clean workspace is the common practice. We could try, though.

**Pull request closed without merging**
