### PR TITLE
HWKAPM-689 | zipkin example nodejs, versions update, sampler setting

### PR DESCRIPTION
**Pull request by pavolloffay**
https://issues.jboss.org/browse/HWKAPM-689

@objectiser could you please review?

Review notes:
Run polyglot-zipkin example with createUser request, dropwizard service should be shown after the first request.

### CODE REVIEW

**Comment by objectiser** [comment]
@pavolloffay Was looking good until the third attempt, which appeared to show the same problem - the node.js to dropwizard link not shown. Wonder why it is always the request to dropwizard that fails, rather than the one from node.js to swarm?

**Comment by pavolloffay** [comment]
I don't know, maybe swarm span overrides the dropwizard span. The call to swarm is second.

**Comment by objectiser** [comment]
But either way, looks like a bug in nodejs impl?

**Comment by objectiser** [comment]
@pavolloffay Thanks!

**Comment by pavolloffay** [comment]
Probably yes, just adding link to following PR with reproducer https://github.com/hawkular/hawkular-apm/pull/635

**Pull request merged**
