### PR TITLE
HWKAPM-640 Set the hostname on trace fragments based on the docker HO…

### PR DESCRIPTION
**Pull request by objectiser**
…STNAME env variable if available

### CODE REVIEW

**Comment by objectiser** [comment]
@pavolloffay can you review please?

Reviewer note:
* Provide accurate hostname in a docker container

**Comment by pavolloffay** [comment]
We should have some example app for testing APM instrumentation as we have for zipkin.

**Comment by objectiser** [comment]
+1 agree -sample app for both opentracing approach and non-intrusive instrumentation,

**Comment by pavolloffay** [comment]
Maybe we should put is also into the setenv script, and just comment it

**Comment by objectiser** [comment]
@pavolloffay Thanks!

**Pull request merged**
